[package]
name = "pdal-sys"
version = "0.1.0"
edition = "2021"

links = "pdal"

[dependencies]
cxx = "1.0.0"
once_cell = "1.19.0"

[build-dependencies]
cmake = "0.1.50"
pkg-config = "0.3"
env_logger = "*"
cxx-build = "1"

[dev-dependencies]
once_cell = "1"

