[env]
CARGO_TARGET_DIR = { value = "target", relative = true }
TEST_DATA_DIR = { value = "tests/data", relative = true }
PKG_DIR = { value = ".", relative = true }

[alias]
# Run clippy, raising warnings to errors
nowarn = "clippy --all-targets -- -D warnings"
coverage = "tarpaulin --out Html --output-dir target --rustflags=-Clink-arg=-lc++"

[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-lc++",
]