[env]
CARGO_TARGET_DIR = { value = "target", relative = true }
TEST_DATA_DIR = { value = "tests/data", relative = true }

[alias]
# Run clippy, raising warnings to errors
nowarn = "clippy --all-targets -- -D warnings"